train:
  log_interval: 200   # step unit
  eval_interval: 400  # step unit
  save_interval: 10  # epoch unit: 50 for baseline / 500 for fine-tuning
  seed: 1234
  epochs: 7000
  learning_rate: 2e-4 
  betas: [0.8, 0.99]
  eps: 1e-9
  batch_size: 32
  fp16_run: True  #False
  lr_decay: 0.999875
  segment_size: 16384 #8192
  c_mel: 45
  c_kl: 1.0
  c_vq: 1.
  c_commit: 0.2
  c_yin: 45.
  log_path: "/logs/"
  n_sample: 3
  alpha: 200

data:
  data_path: "./dataset/jvs_ver1/"
  training_files: "./filelists/jvs_train_44100.txt"
  validation_files: "./filelists/jvs_val_44100.txt"
  languages: "pyopenjtalk_prosody" 
  text_cleaners: []
  sampling_rate: 44100 #22050 
  filter_length: 2048 #1024 
  hop_length: 512 #256 
  win_length: 2048 #1024
  n_mel_channels: 80
  mel_fmin: 0.0
  mel_fmax: null
  add_blank: True
  speakers: ['jvs001', 'jvs002', 'jvs003', 'jvs004', 'jvs005', 'jvs006', 'jvs007', 'jvs008', 'jvs009', 'jvs010', 'jvs011', 'jvs012', 'jvs013', 'jvs014', 'jvs015', 'jvs016', 'jvs017', 'jvs018', 'jvs019', 'jvs020', 'jvs021', 'jvs022', 'jvs023', 'jvs024', 'jvs025', 'jvs026', 'jvs027', 'jvs028', 'jvs029', 'jvs030', 'jvs031', 'jvs032', 'jvs033', 'jvs034', 'jvs035', 'jvs036', 'jvs037', 'jvs038', 'jvs039', 'jvs040', 'jvs041', 'jvs042', 'jvs043', 'jvs044', 'jvs045', 'jvs046', 'jvs047', 'jvs048', 'jvs049', 'jvs050', 'jvs051', 'jvs052', 'jvs053', 'jvs054', 'jvs055', 'jvs056', 'jvs057', 'jvs058', 'jvs059', 'jvs060', 'jvs061', 'jvs062', 'jvs063', 'jvs064', 'jvs065', 'jvs066', 'jvs067', 'jvs068', 'jvs069', 'jvs070', 'jvs071', 'jvs072', 'jvs073', 'jvs074', 'jvs075', 'jvs076', 'jvs077', 'jvs078', 'jvs079', 'jvs080', 'jvs081', 'jvs082', 'jvs083', 'jvs084', 'jvs085', 'jvs086', 'jvs087', 'jvs088', 'jvs089', 'jvs090', 'jvs091', 'jvs092', 'jvs093', 'jvs094', 'jvs095', 'jvs096', 'jvs097', 'jvs098', 'jvs099', 'jvs100']
  persistent_workers: True
  midi_start: -5
  midi_end: 75
  midis: 80
  ying_window: 4096 #2048 =tau_max
  ying_hop: 512 #256   
  tau_max: 4096 #2048  diff maximum period
  octave_range: 24
  
model:
  inter_channels: 192
  hidden_channels: 192
  filter_channels: 768
  n_heads: 2
  n_layers: 6
  kernel_size: 3
  p_dropout: 0.1
  resblock: "1"
  resblock_kernel_sizes: [3,7,11]
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
  upsample_rates: [8,8,2,2,2] #[8,8,2,2]
  upsample_initial_channel: 512
  upsample_kernel_sizes: [16,16,4,4,4] #[16,16,4,4]
  n_layers_q: 3
  use_spectral_norm: False
  gin_channels: 256
  codebook_size: 320
  yin_channels: 80
  yin_start: 15 # scope start bin in nansy = 1.5/8 
  yin_scope: 50 # scope ratio in nansy = 5/8 
  yin_shift_range: 15 # same as default start index of yingram
